# Generated by Django 5.1.6 on 2025-02-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=400)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
