# Generated by Django 5.1.6 on 2025-02-24 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=400)),
                ('image', models.ImageField(upload_to='groupImage/')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagepost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
